classDiagram

%%==========================
%% PESSOAS
%%==========================

class Person{
    +id
    +name
    +login()
    +searchItems()
    +viewItems()
}

class Visitor{
    +donateBook()
}

class AcademicMember{
    +borrowItem()
    +donateBook()
}

class Student

class Professor{
    +borrowForStudent()
    +reserveItem()
    +requestRestrictedAccess()
}

class Librarian{
    +registerPerson()
    +updatePerson()
    +registerItem()
    +updateItem()
    +registerResearch()
    +sanctionUser()
    +cancelReservation()
    +cancelLoan()
    +cancelRestrictedConsultation()
}

Person <|-- Visitor
Person <|-- AcademicMember
Person <|-- Librarian

AcademicMember <|-- Student
AcademicMember <|-- Professor


%%==========================
%% PESQUISA
%%==========================

class Research{
    -title
    -description
    -members : vector~AcademicMember~
    +publish()
    +reserveItem()
    +scheduleRestrictedConsultation()
}

Research "1" *-- "1..*" AcademicMember : researchers


%%==========================
%% ITENS
%%==========================

class Item{
    +id
    +title
}

class PublicItem

class RestrictedItem

class LoanableItem{
    +borrow()
    +returnItem()
    +reserve()
}

class ExhibitionItem{
    +view()
}

Item <|-- PublicItem
Item <|-- RestrictedItem

PublicItem <|-- LoanableItem
PublicItem <|-- ExhibitionItem
