classDiagram

class Item {
    <<abstract>>
    - Status status
    + string id
    + string name
    + accessItem()*
    + setStatus(Status)
    + getStatus() Status
}

class PublicItem {
    - string DisplayArea
    + accessItem()
    + setDisplayArea(string)
}

class LoanableItem {
    + string responsibleId
    + accessItem()
}

class ExhibitionItem {
    + setDisplayArea(string)
    + accessItem()
}

class RestrictedItem {
    + Visit AccessAppointments[4][2]
    + setStatus(Status)
    + accessItem()
    + getAvailableAppointments()
    + printHorario(Horarios)
}

class Visit {
    + time_t dia
    + Horarios horario
    + AcademicMember* participantes[5]
    + VisitStatus VisitState
}

class Person {
    <<interface>>
    + searchItem()*
}

class AcademicMember {
    + string name
    + string matricula
    + int maxActiveLoans
    + int ActiveLoans
    + searchItem()
    + BorrowItem(vector<LoanableItem>&, string)
    + ReturnItem(vector<LoanableItem>&, string)
}

class Student {
    + static int DefaultMaxActiveLoans
}

class Professor {
    + static int DefaultMaxActiveLoans
    + RequestRestrictedAccess()
}

class Status {
    <<enumeration>>
    BORROWED
    AVAILABLE
    UNAVAILABLE
}

class VisitStatus {
    <<enumeration>>
    SCHEDULED
    AVAILABLE
    UNAVAILABLE
}

class Horarios {
    <<enumeration>>
    M56
    T34
    N12
}

%% HERANÇAS
Item <|-- PublicItem
PublicItem <|-- LoanableItem
PublicItem <|-- ExhibitionItem
Item <|-- RestrictedItem

Person <|.. AcademicMember
AcademicMember <|-- Student
AcademicMember <|-- Professor

%% RELAÇÕES
RestrictedItem *-- Visit : agenda
AcademicMember --> LoanableItem : borrow/return
Visit --> AcademicMember : participants
